version: 2
workflows:
  version: 2
  test:
    jobs:
      - test-2.0
jobs:
  test-2.0:
    docker:
      - image: mcr.microsoft.com/dotnet/core/sdk:2.1-focal
      - image: consul
    steps:
      - checkout
      - run: dotnet restore
      - run: dotnet build src/LaunchDarkly.ServerSdk.Consul -f netstandard2.0
      - run: dotnet test test/LaunchDarkly.ServerSdk.Consul.Tests -f netcoreapp2.1
