publications:
  - url: https://nuget.org/packages/LaunchDarkly.ServerSdk.Consul
    description: NuGet

circleci:
  windows:
    context: org-global
    env:
      LD_RELEASE_DOCS_TARGET_FRAMEWORK: netstandard2.0

template:
  name: dotnet-windows
  skip:
    - test  # tests require Consul - run them only in CI

documentation:
  title: LaunchDarkly SDK Consul Integration
  githubPages: true
