version: 2

publications:
  - url: https://nuget.org/packages/LaunchDarkly.ServerSdk.Consul
    description: NuGet

branches:
  - name: main
    description: 3.x - for SDK 6+, with new Consul client
  - name: 2.x
    description: for SDK 6+, with old Consul client
  - name: 1.x
    description: for SDK 5.x

jobs:
  - docker: {}
    template:
      name: dotnet-linux
      skip:
        - test
    env:
      LD_RELEASE_DOCS_TARGET_FRAMEWORK: netstandard2.0

documentation:
  title: LaunchDarkly Server-Side .NET SDK Consul Integration
  gitHubPages: true
