publications:
  - url: https://nuget.org/packages/LaunchDarkly.ServerSdk.Consul
    description: NuGet

releasableBranches:
  - name: master
    description: 2.x - for SDK 6+
  - name: 1.x
    description: for SDK 5.x

circleci:
  windows:
    context: org-global
    env:
      LD_RELEASE_DOCS_TARGET_FRAMEWORK: net452

template:
  name: dotnet-windows
  skip:
    - test

documentation:
  title: LaunchDarkly Server-Side .NET SDK Consul Integration
  githubPages: true
