
publications:
  - url: https://nuget.org/packages/LaunchDarkly.ServerSdk.Consul
    description: NuGet

circleci:
  windows:
    context: org-global

template:
  name: dotnet-windows
  skip:
    - test
  env:
    LD_RELEASE_DOCS_TARGET_FRAMEWORK: netstandard2.0

documentation:
  title: LaunchDarkly Server-Side .NET SDK Consul Integration
  githubPages: true
