name: CI
description: Runs CI for the .NET Server SDK
inputs:
  sdk:
    description: 'The dotnet SDK to use.'
    required: false
    default: '9'

runs:
  using: composite
  steps:
    - uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ inputs.sdk }}
    - run: dotnet restore src/LaunchDarkly.ServerSdk.Consul
      shell: bash
    - run: dotnet build src/LaunchDarkly.ServerSdk.Consul
      shell: bash
    - run: dotnet test test/LaunchDarkly.ServerSdk.Consul.Tests
      shell: bash
