name: Build and Test

on:
  push:
    branches: [main, 'feat/**']
    paths-ignore:
      - '**.md' #Do not need to run CI for markdown changes.
  pull_request:
    branches: [main, 'feat/**']
    paths-ignore:
      - '**.md'
  workflow_call:

jobs:
  build-test-linux:
    services:
      consul:
        image: hashicorp/consul
        ports:
          - 8500:8500

    runs-on: ubuntu-latest
    strategy:
      matrix:

          dotnet: [{sdk: '8.x'}, {sdk: '9.x'}]
    name: Build - ${{ matrix.dotnet.sdk }}
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/ci
        with:
          sdk: ${{ matrix.dotnet.sdk }}
